// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseExcelFile() {
  return window['go']['main']['App']['ChooseExcelFile']();
}

export function GetAppMeta() {
  return window['go']['main']['App']['GetAppMeta']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RegisterFromExcel(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterFromExcel'](arg1, arg2, arg3);
}
