// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseExcelFile():Promise<string>;

export function GetAppMeta():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function RegisterFromExcel(arg1:string,arg2:string,arg3:string):Promise<Record<string, number>>;
